### ISSUE TITLE
大佬，这个怎么使用

### ISSUE THREAD

**Issue by tudan110** [inclyc/containerized-topsap#3]
大佬，能否讲解一下怎么使用

**Comment by inclyc** [comment]
参考 https://github.com/inclyc/containerized-topsap/pkgs/container/containerized-topsap 运行容器，然后可以对外开放一个 socks5 代理使用，具体用法和 https://github.com/Hagb/docker-easyconnect 差不多

**Comment by tudan110** [comment]
感谢，我研究一下

**Comment by inclyc** [comment]
```console
$ podman run --rm --privileged --env-file=$HOME/.config/topsap/envfile --device /dev/net/tun --cap-add NET_ADMIN --sdnotify=conmon --log-driver=journald  -d -p 127.0.0.1:1080:1080 --name topsap ghcr.io/inclyc/containerized-topsap
```

envfile 的内容：

```
TOPVPN_SERVER=服务器
TOPVPN_USERNAME=用户名
TOPVPN_PASSWORD=密码
```

这个指令暴露一个端口在 1080 的 socks5 代理，可供ssh使用

**Comment by tudan110** [comment]
> ```
> $ podman run --rm --privileged --env-file=$HOME/.config/topsap/envfile --device /dev/net/tun --cap-add NET_ADMIN --sdnotify=conmon --log-driver=journald  -d -p 127.0.0.1:1080:1080 --name topsap ghcr.io/inclyc/containerized-topsap
> ```
> 
> envfile 的内容：
> 
> ```
> TOPVPN_SERVER=服务器
> TOPVPN_USERNAME=用户名
> TOPVPN_PASSWORD=密码
> ```
> 
> 这个指令暴露一个端口在 1080 的 socks5 代理，可供ssh使用

谢谢
